http://localhost:3000/books

### return books between min & max price

http://localhost:3000/books?minPrice=300&maxPrice=400


### bad values

http://localhost:3000/books?minPrice=none&maxPrice=none


### bad params

http://localhost:3000/books?babyPoop=true


